<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://ploinky.de/mySchema"
    elementFormDefault="qualified"
> 

<xs:element name="map">
    <xs:complexType>
        <xs:all>
            <xs:element name="navmesh" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="file" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="camvolume" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="back" type="xs:float" use="required" />
                    <xs:attribute name="front" type="xs:float" use="required" />
                    <xs:attribute name="left" type="xs:float" use="required" />
                    <xs:attribute name="right" type="xs:float" use="required" />
                    <xs:attribute name="top" type="xs:float" use="required" />
                    <xs:attribute name="bottom" type="xs:float" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="model" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

</xs:schema>