<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://ploinky.de/mySchema"
    elementFormDefault="qualified"
> 

<xs:element name="entity">
    <xs:complexType>
        <xs:all>
            <xs:element name="abilities" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="ability" minOccurs="0" maxOccurs="4">
                            <xs:complexType>
                                <xs:attribute name="id" type="xs:string" use="required" />
                                <xs:attribute name="slot" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="0"/>
                                            <xs:maxInclusive value="3"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                    <xs:attribute name="move_speed" type="xs:float" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="transform" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="collision_radius" type="xs:int" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="network" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="sync_movement" type="xs:boolean" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="movement" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="speed" type="xs:int" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="health" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="max_health" type="xs:int" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="targetable" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="selection_radius" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="navigation" minOccurs="0" maxOccurs="1">
                <xs:complexType></xs:complexType>
            </xs:element>
            <xs:element name="intent" minOccurs="0" maxOccurs="1">
                <xs:complexType></xs:complexType>
            </xs:element>
            <xs:element name="audio" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="death" type="xs:string" use="optional" />
                    <xs:attribute name="attack1" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="pickupable" minOccurs="0" maxOccurs="1">
                <xs:complexType></xs:complexType>
            </xs:element>
            <xs:element name="useable" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="abilityId" type="xs:string" use="required"/>
                    <xs:attribute name="uses" type="xs:positiveInteger" use="optional"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="inventory" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <!--
                    <xs:attribute name="slots" type="xs:positiveInteger" use="required"/>
                    -->
                </xs:complexType>
            </xs:element>
            <xs:element name="ai" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="type" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="model" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

</xs:schema>