#pragma once

enum class PacketType {
	// Finding servers
	SERVER_INFO,

	// Lobby handling
	LOBBY_PLAYER_PCK,
	PCK_LOBBY_PLAYER_LEFT,
	LOBBY_CMD_SLOT,
	LOBBY_PCK_READY,
	LOBBY_CMD_READY,
	LOBBY_GAME_START,

	// Character Select
	CHARACER_SELECT_REMAINING_TIME,

	// Gameplay
	UNITSPAWN,
	UNITMOVE,
	UNITMOVE_INTENTION,
	UNITIDLE,
	UNITDESPAWN,
	GAME_TICK,
	PCK_NAME_REQUEST,
	CMD_READY,
	CMD_NOT_READY,
	CMD_STOP,
	CMD_ATTACK,
	CMD_CAST,
	CMD_CAST_TARGET,
	PCK_CLIENT_UNIT_ID,
	PCK_STATS,
	PCK_SPELL_COOLDOWN,
	PCK_PLAY_PARTICLE,
	PCK_ATTACK_START,
	SCORE_UPDATE_PACKET,
	GAME_END_PACKET,
	MOVE_CMD,

	PCK_SPELL_CAST_START,
	PCK_SPELL_HIT,

	PCK_UNIT_DEATH,
	PCK_UNIT_RESPAWN,

	// OTHER?
	SERVER_MESSAGE
};